name: Update lockfiles

on:
  schedule:
    - cron: '0 3 * * *' # Every Monday at 03:00 UTC
  workflow_dispatch:

env:
  HATCH_VERSION: "1.16.2"

jobs:
  update-pre-commit-config:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Set up Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: '3.14'
          cache: 'pip'

      - name: Install Hatch
        uses: pypa/hatch@install
        with:
          version: "${{ env.HATCH_VERSION }}"

      - name: Update lockfiles
        run: hatch run hatch-pip-compile --upgrade --all

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@84ae59a2cdc2258d6fa0732dd66352dddae2a412 # v7.0.9
        with:
          commit-message: "chore(deps): Update lockfiles"
          title: "chore(deps): Update lockfiles"
          body: "Automated update of lockfiles via scheduled workflow."
          branch: "update/lockfiles"
          base: ${{ github.ref_name }}
          labels: "update"
          reviewers: "linuxdaemon"
          assignees: "linuxdaemon"
          sign-commits: true
