name: Update lockfiles

on:
  schedule:
    - cron: '0 3 * * *' # Every Monday at 03:00 UTC
  workflow_dispatch:

env:
  HATCH_VERSION: "1.15.1"

jobs:
  update-pre-commit-config:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6
        with:
          python-version: '3.14'
          cache: 'pip'

      - name: Install Hatch
        uses: pypa/hatch@install
        with:
          version: "${{ env.HATCH_VERSION }}"

      - name: Update lockfiles
        run: hatch run hatch-pip-compile --upgrade --all

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@84ae59a2cdc2258d6fa0732dd66352dddae2a412 # v7.0.9
        with:
          commit-message: "chore(deps): Update lockfiles"
          title: "chore(deps): Update lockfiles"
          body: "Automated update of lockfiles via scheduled workflow."
          branch: "update/lockfiles"
          base: ${{ github.ref_name }}
          labels: "update"
          reviewers: "linuxdaemon"
          assignees: "linuxdaemon"
          sign-commits: true
